### ISSUE TITLE
Make gitflow plugin compatible

### ISSUE THREAD

**Issue by ligoj** [ligoj/bootstrap#1]
The structure of LB is not well understood by `maven-release-plugin:update-versions` executed by gitflow-maven-plugin
Error : 
```
[DEBUG] release.properties not found - using empty properties
[INFO] Transforming 'Ligoj - Bootstrap - Parent'...
[INFO]   Updating ${bootstrap.version} to 0.0.0-SNAPSHOT
[INFO]   Ignoring artifact version update for expression ${bootstrap.version} because it is already updated
[INFO]   Ignoring artifact version update for expression ${bootstrap.version} because it is already updated
[INFO] Transforming 'bootstrap-core'...
[INFO] Transforming 'bootstrap-launcher'...
[INFO] Transforming 'bootstrap-business-test'...
[INFO]   Ignoring artifact version update for expression ${project.version}
[INFO]   Ignoring artifact version update for expression ${project.version}
[INFO] Transforming 'bootstrap-business'...
[INFO]   Ignoring artifact version update for expression ${project.version}
[INFO] Transforming 'bootstrap-business-parent'...
[INFO] Transforming 'bootstrap-web-test'...
[INFO]   Ignoring artifact version update for expression ${project.version}
[INFO] Transforming 'bootstrap-web'...
```

And then : 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:update-versions (default-cli) on project root: The version could not be updated: ${bootstrap.version} -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:update-versions (default-cli) on project root: The version could not be updated: ${bootstrap.version}
...
Caused by: org.apache.maven.shared.release.ReleaseFailureException: The version could not be updated: ${bootstrap.version}
        at org.apache.maven.shared.release.phase.AbstractRewritePomsPhase.rewriteArtifactVersions(AbstractRewritePomsPhase.java:593)
        at org.apache.maven.shared.release.phase.AbstractRewritePomsPhase.transformDocument(AbstractRewritePomsPhase.java:289)
```

**Comment by fdaugan** [comment]
Fixed with VueJS migration
